### ISSUE TITLE
SQLMap fails

### ISSUE THREAD

**Issue by DeviaVir** [pebble/golismero-suite#6]
```
[*] SQLMap (12): Launching SQLMap against: http://pebble.com/choose_region?from=%2F
[*] SQLMap (12): Traceback (most recent call last):
[*] SQLMap (12):   File "/opt/golismero/tools/sqlmap/sqlmap.py", line 22, in <module>
[*] SQLMap (12):     from lib.controller.controller import start
[*] SQLMap (12):   File "/opt/golismero/tools/sqlmap/lib/controller/controller.py", line 60, in <module>
[*] SQLMap (12):     from lib.core.target import initTargetEnv
[*] SQLMap (12):   File "/opt/golismero/tools/sqlmap/lib/core/target.py", line 40, in <module>
[*] SQLMap (12):     from lib.core.option import _setDBMS
[*] SQLMap (12):   File "/opt/golismero/tools/sqlmap/lib/core/option.py", line 140, in <module>
[*] SQLMap (12):     from lib.request.httpshandler import HTTPSHandler
[*] SQLMap (12):   File "/opt/golismero/tools/sqlmap/lib/request/httpshandler.py", line 22, in <module>
[*] SQLMap (12):     _protocols = [ssl.PROTOCOL_SSLv3, ssl.PROTOCOL_TLSv1, ssl.PROTOCOL_SSLv23]
[*] SQLMap (12): AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
[*] SQLMap (12): SQLMap scan finished in 0.685098171234 seconds for target: http://pebble.com/choose_region?from=%2F
[!] SQLMap (12): [Errno 2] No such file or directory: '/tmp/tmpTQG4lT/pebble.com/log'
[*] SQLMap (12): No SQL injection vulnerabilities found.
```

**Comment by riaje** [comment]
Golismero need update sqlmap tool :
https://github.com/sqlmapproject/sqlmap/commit/a0d95a8ec49ab0b41bd39c2bb537cb1d9bc07b9d

For a temporary solution open [GOLISMERO PROJET]/tools/sqlmap/lib/request/httpshandler.py
Replace line 22 to :
+_protocols = filter(None, (getattr(ssl, _, None) for _ in ("PROTOCOL_SSLv3", "PROTOCOL_TLSv1", "PROTOCOL_SSLv23", "PROTOCOL_SSLv2")))
